abs_path: /Users/yangyu/Desktop/MT5ForGeneration/

t5model_path: mt5_model/mt5-small-simplify

dataset_path: data_preprocess/clear2.txt
train_path: data_preprocess/train.txt
test_path: data_preprocess/test.txt

train_tiny_path: data_preprocess/tiny/train.txt
test_tiny_path: data_preprocess/tiny/test.txt

cache_train_path: data_preprocess/train_cache.bin
cache_test_path: data_preprocess/test_cache.bin

train_rate: 0.9

use_cuda: True

batch_size: 32
LR: 0.002
EPOCH: 100
