abs_path: /home/yangyu/判决生成/

t5model_path: mt5_model/mt5-base

dataset_path: data_preprocess/clear2.txt
train_path: data_preprocess/train.txt
test_path: data_preprocess/test.txt

train_tiny_path: data_preprocess/tiny/train.txt
test_tiny_path: data_preprocess/tiny/test.txt

train_rate: 0.9

use_cuda: True

batch_size: 1
LR: 0.0002
EPOCH: 10
